spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/Products?useSSL=false&amp
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jmx:
    enabled: true

management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:

        include: "*"


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


